In [2]:
words = open('../names.txt', 'r').read().splitlines()

In [10]:
words[:11]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn',
 'abigail']

In [7]:
min(len(word) for word in words)

2

In [9]:
max(len(word) for word in words)

15

In [11]:
# developing a weak bigram language model (only looking for two characters at a time, looking at one char and predicting next one)

for word in words[:3]: # demonstrate on first word
    # in this word, iterate through it to get two chars at a time
    with_special_characters = ['<START>'] + list(word) + ['<END>'] # separate each word with special characters
    for ch1, ch2 in zip(with_special_characters, with_special_characters[1:]): # interate through word, and word starting at second character so that you don't get (e, e) for emma for example
        print(ch1, ch2)

<START> e
e m
m m
m a
a <END>
<START> o
o l
l i
i v
v i
i a
a <END>
<START> a
a v
v a
a <END>


In [17]:
# count how often each bigram occurs -- stats
# need dict to maintain count

bigram_counts = {} # empty dict
for word in words:
    # in this word, iterate through it to get two chars at a time
    with_special_characters = ['<START>'] + list(word) + ['<END>'] # separate each word with special characters
    for ch1, ch2 in zip(with_special_characters, with_special_characters[1:]): # interate through word, and word starting at second character so that you don't get (e, e) for emma for example
       bigram_counts_index = (ch1, ch2) # tuple
       bigram_counts[bigram_counts_index] = bigram_counts.get(bigram_counts_index, 0) + 1 # get the count of the bigram, if it doesn't exist, return 0 and add 1 to it

# This will return something like:
# {('<START>', 'e'): 1}
# {('<START>', 'e'): 1, ('e', 'm'): 1}
# {('<START>', 'e'): 1, ('e', 'm'): 1, ('m', 'm'): 1}
# {('<START>', 'e'): 1, ('e', 'm'): 1, ('m', 'm'): 1, ('m', 'a'): 1}


In [23]:
sorted(bigram_counts.items(), key = lambda kv: -kv[1]) # kv: -kv[1] sorts by the second item in the dict, ie. the count. Negative sorts descending

[(('n', '<END>'), 6763),
 (('a', '<END>'), 6640),
 (('a', 'n'), 5438),
 (('<START>', 'a'), 4410),
 (('e', '<END>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<START>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<START>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<END>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<START>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<END>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<START>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<END>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<START>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<START>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<START>', 'l'), 1572),
 (('<START>', 'c'), 1542)

In [31]:
%pip install torch


     |████████████████████████████████| 146.7 MB 1.9 MB/s eta 0:00:01
     |████████████████████████████████| 2.1 MB 7.3 MB/s eta 0:00:01
     |████████████████████████████████| 5.7 MB 2.2 MB/s eta 0:00:01
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
  Using cached fsspec-2023.9.2-py3-none-any.whl (173 kB)
  Using cached MarkupSafe-2.1.3-cp38-cp38-macosx_10_9_x86_64.whl (13 kB)
     |████████████████████████████████| 536 kB 6.3 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [32]:
import torch

/opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [41]:
a = torch.zeros((3, 5), dtype=torch.int32) # example
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [50]:
a[0, 0] = 1 # this is how you set a value in a tensor
a

tensor([[1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [61]:
%pip install matplotlib numpy

     |████████████████████████████████| 19.8 MB 5.4 MB/s eta 0:00:01     |██████████████████              | 11.2 MB 2.4 MB/s eta 0:00:04
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.4
    Uninstalling numpy-1.24.4:
      Successfully uninstalled numpy-1.24.4
Note: you may need to restart the kernel to use updated packages.


In [152]:
neural_net = torch.zeros((28, 28), dtype=torch.int32) # building neural net of character array

unique_chars = list(set(''.join(words))) # get all unique characters and transform into list
alphabetrical_unique_chars = sorted(unique_chars)
stoi = {ch: i+1 for i, ch in enumerate(alphabetrical_unique_chars)} # string to index
itos = {i: ch for ch, i in stoi.items()} # index to string
stoi['<START>'] = 26
stoi['<END>'] = 27
stoi['.'] = 0
itos[0] = '.'

# transform into array
for word in words:
    # in this word, iterate through it to get two chars at a time
    with_special_characters = ['.'] + list(word) + ['.'] # separate each word with special characters
    for ch1, ch2 in zip(with_special_characters, with_special_characters[1:]): # interate through word, and word starting at second character so that you don't get (e, e) for emma for example
       # accessed slightly differently from first example given pytorch constraints
       index_one = stoi[ch1]
       index_two = stoi[ch2]
       neural_net[index_one, index_two] += 1 # filling out the empty neural net array with the character counts

neural_net ## identical to the weights we have later, but filled in by counting, whereas in gradient optimization we initialize randomly then let loss guide us to the right numbers
## also a valid way to train, probably just not very scalable / efficient. If you take more context (ex. 3 chars, or 4) this array just expands and expands

tensor([[   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
         1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
          134,  535,  929,    0],
        [6640,  556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568,
         2528, 1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,
          182, 2050,  435,    0],
        [ 114,  321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,
          103,    0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,
            0,   83,    0,    0],
        [  97,  815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,
          116,    0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,
            3,  104,    4,    0],
        [ 516, 1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,
           60,   30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,
            0,  317,    1,    0],
        [3983,  679,

In [153]:
neural_net[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929,    0], dtype=torch.int32)

In [155]:
probability_vector = neural_net[0].float() # convert into float to normalize the counts
probability_vector / probability_vector.sum() # normalize the counts
probability_vector

tensor([   0., 4410., 1306., 1542., 1690., 1531.,  417.,  669.,  874.,  591.,
        2422., 2963., 1572., 2538., 1146.,  394.,  515.,   92., 1639., 2055.,
        1308.,   78.,  376.,  307.,  134.,  535.,  929.,    0.])

In [176]:
generator = torch.Generator().manual_seed(10328361) # set seed for reproducibility
probability_vector = torch.rand(3, generator=generator)
probability_vector = probability_vector / probability_vector.sum()
index = torch.multinomial(probability_vector, num_samples=1, replacement=True, generator=generator).item() # sample from the probability vector
itos[index]

'.'

In [179]:
generator = torch.Generator().manual_seed(10328361)

for i in range(50):
    out = []
    index = 0

    while True:
        probability_vector = neural_net[index].float() # convert into float to normalize the counts, gets probabilities of chars in bigram neural net
        probability_vector = probability_vector / probability_vector.sum()

        ## uniform distribution that makes everything equally likely, not 'trained' like above
        # probability_vector = torch.ones(28) / 28

        index = torch.multinomial(probability_vector, num_samples=1, replacement=True, generator=generator).item() # gets a sample from the multinomial distribution, like m, or a
        out.append(itos[index])
        if index == 0:
            break
        
    print(''.join(out))

iae.
nl.
madan.
ma.
k.
a.
cha.
satammeralesynda.
noh.
giceleyyn.
avyr.
s.
lyh.
borasy.
t.
ti.
sh.
la.
zyn.
rimi.
dannn.
vyaniahl.
toyrvia.
cowonichrzarilalllavaran.
aicamelazezos.
n.
arha.
n.
aua.
tan.
sheilelynanah.
listoro.
teryomare.
thayla.
shantti.
lyaneorielelecilos.
akadevon.
jeysee.
kon.
olaweyllavali.
iraveismun.
atenngtoto.
di.
ann.
kishialay.
bey.
jeluelentu.
kyath.
liguxila.
e.


In [182]:
# instead of a statistical model, now we are going to pass this into a neural network
xs, ys = [], []

for word in words[:1]: # Emma
    with_special_characters = ['.'] + list(word) + ['.'] # separate each word with special characters
    for ch1, ch2 in zip(with_special_characters, with_special_characters[1:]): # interate through word, and word starting at second character so that you don't get (e, e) for emma for example
       index_one = stoi[ch1]
       index_two = stoi[ch2]
       print(ch1, ch2) # Five examples for neural network
       xs.append(index_one)
       ys.append(index_two)

xs = torch.tensor(xs)
ys = torch.tensor(ys)

. e
e m
m m
m a
a .


In [185]:
xs

tensor([ 0,  5, 13, 13,  1])

In [186]:
ys

tensor([ 5, 13, 13,  1,  0])

In [189]:
# In the above, when input to neural network xs[0] = 0, we want ys[0] = 5 to have a very high probability, and so forth

# Now, let's feed these examples into a neural network, where neural nodes have weights. It doesn't really make sense to feed integers into the data to multiply by the weights, we want vectors of floats
# We should fill in a tensor (vector) which corresponds to that integer but represented in vector form
# appropriate bits are one, everything else is zero

import torch.nn.functional as F
x_encoded = F.one_hot(xs, num_classes=27).float()
x_encoded


tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [197]:
Weights = torch.randn((27, 1)) # random initialized weights, as an example neural network
Weights

tensor([[ 2.0199],
        [ 0.0718],
        [-0.5823],
        [-0.9975],
        [ 0.1654],
        [ 0.0177],
        [ 0.8005],
        [ 0.1831],
        [ 1.6134],
        [-0.1869],
        [ 0.0305],
        [-0.1526],
        [ 1.2124],
        [-0.0083],
        [ 0.0510],
        [-1.6765],
        [ 0.6808],
        [-0.1999],
        [-0.0611],
        [-2.6551],
        [-0.8364],
        [-0.8796],
        [ 0.3318],
        [-0.1856],
        [-0.2666],
        [-0.2334],
        [-0.6123]])

In [198]:
x_encoded @ Weights # dot product; we're seeing the five activations of the weight (neuron) on the five inputs (x_encoded)

tensor([[ 2.0199],
        [ 0.0177],
        [-0.0083],
        [-0.0083],
        [ 0.0718]])

In [206]:
(x_encoded @ Weights).exp() # get rid of the zeroes

tensor([[ 0.5851,  9.2431,  0.4207,  0.9388,  0.4330,  0.5203,  0.4035,  5.7702,
          0.6945,  1.0163,  0.1915, 12.5951,  0.9829,  1.8943,  1.2268,  3.8488,
          2.7527,  1.7713,  2.5241,  4.3175,  0.9236,  2.1941,  1.8778,  0.5048,
          2.6747,  2.0480,  2.3330],
        [ 1.3708,  6.8282,  1.4400,  0.8908,  1.2035,  0.8037,  1.5452,  6.2404,
          1.9076,  0.0745,  3.4202,  2.1633,  0.8062,  1.1703,  0.4999,  0.2970,
          0.6500,  1.7589,  0.1513,  0.2544,  2.0055,  1.4690,  0.7045,  0.3609,
          0.2396,  0.5369,  1.1744],
        [ 0.9580,  0.1552,  3.3532,  0.1754,  0.7790,  0.5762,  0.6652,  0.1994,
          0.3455,  0.5957,  0.6131,  0.2873,  1.6419,  1.6819,  1.0969,  7.2752,
          2.3565,  2.1887,  1.8467,  0.7262,  1.6893,  0.3844,  2.5566,  1.6272,
          1.5724,  6.7502,  0.5078],
        [ 0.9580,  0.1552,  3.3532,  0.1754,  0.7790,  0.5762,  0.6652,  0.1994,
          0.3455,  0.5957,  0.6131,  0.2873,  1.6419,  1.6819,  1.0969,  7.2752

In [228]:
#### Do a forward pass, the above is just demo code ####
Weights = torch.randn((27, 27), generator = generator, requires_grad=True) # you need requires_grad or the autograd system won't track these tensors
x_encoded = F.one_hot(xs, num_classes=27).float()
logits = x_encoded @ Weights
counts = logits.exp() 
probs = counts / counts.sum(1, keepdims = True) # Gives us our probability tensor we'll index into for the next token

# For example where xs = tensor([0, 5, 13, 13, 1]) and ys = tensor([5, 13, 13, 1, 0]) we are trying to find the probability of the character in the prob_tensor at index 5 (corresponding with ys)
print(probs[0, 5]) # probability of the character in the prob_tensor at index 5 (corresponding with ys[0])

print(probs[1, 13]) # probability of the character in the prob_tensor at index 13 (corresponding with ys[1])

print(probs[2, 13]) # probability of the character in the prob_tensor at index 13 (corresponding with ys[2])

print(probs[3, 1])

print(probs[4, 0]) # and so forth

tensor(0.0178, grad_fn=<SelectBackward0>)
tensor(0.0254, grad_fn=<SelectBackward0>)
tensor(0.0271, grad_fn=<SelectBackward0>)
tensor(0.0444, grad_fn=<SelectBackward0>)
tensor(0.0232, grad_fn=<SelectBackward0>)


In [229]:
# Another way of writing the print statements above
x_axis = torch.arange(5)
probabilities = probs[x_axis, ys]
probabilities

tensor([0.0178, 0.0254, 0.0271, 0.0444, 0.0232], grad_fn=<IndexBackward0>)

In [230]:
# computing the log likelihood of the data -- we'll go for minimizing the negative log likelihood
loss = -probabilities.log().mean()
loss

tensor(3.6368, grad_fn=<NegBackward0>)

In [ ]:
#### Do a backward pass ####
Weights.grad = None # reset the weights in the network
loss.backward() # compute the gradients

In [232]:
Weights.grad # Each elements tells us the influence of a given weight on the launch function; if the gradient is positive, increasing the weight will increase the loss, and if negative increasing the weight will reduce loss

tensor([[ 0.0051,  0.0023,  0.0044,  0.0010,  0.0024, -0.1964,  0.0051,  0.0189,
          0.0092,  0.0041,  0.0135,  0.0044,  0.0035,  0.0091,  0.0223,  0.0141,
          0.0007,  0.0038,  0.0076,  0.0038,  0.0049,  0.0087,  0.0040,  0.0122,
          0.0045,  0.0231,  0.0033],
        [-0.1954,  0.0034,  0.0010,  0.0156,  0.0149,  0.0064,  0.0055,  0.0160,
          0.0065,  0.0168,  0.0018,  0.0159,  0.0043,  0.0059,  0.0024,  0.0016,
          0.0130,  0.0058,  0.0065,  0.0100,  0.0118,  0.0013,  0.0018,  0.0060,
          0.0055,  0.0057,  0.0100],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000

In [244]:
#### Update the weights ####
Weights.data += -0.1 * Weights.grad # update the weights, reducing them to decrease the loss

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [243]:
# If I now recalculate the forward pass, the loss should be lower
x_encoded = F.one_hot(xs, num_classes=27).float()
logits = x_encoded @ Weights
counts = logits.exp() 
probs = counts / counts.sum(1, keepdims = True) # Gives us our probability tensor we'll index into for the next token
x_axis = torch.arange(5)
probabilities = probs[x_axis, ys]
loss = -probabilities.log().mean()
loss

# As you can see above, loss decreased by 0.1

tensor(3.5363, grad_fn=<NegBackward0>)

In [285]:
###### Now, let's put this all together to train a neural network over the entire list of names ######

### 1. Build the dataset
words = open('../names.txt', 'r').read().splitlines()
xs, ys = [], []

for word in words:
    characters = ['.'] + list(word) + ['.'] # separate each word with special characters
    for characters[1], characters[2] in zip(characters, characters[:1]):
        index1 = stoi[characters[1]]
        index2 = stoi[characters[2]]
        xs.append(index1)
        ys.append(index2)
xs = torch.tensor(xs) # Corresponds to rows in the weights tensor
ys = torch.tensor(ys) # Correspond to the columns matched up with the rows in the weights tensor, what the 'actual' outputs should be

number_of_examples = xs.nelement() # should be 32033

### 2. Initialize the toy network with randomized weights
g = torch.Generator().manual_seed(10328361)
Weights = torch.rand((27, 27), generator=g, requires_grad=True) # What network expects output of input x_axis to be



In [303]:
### 3. Carry out gradient descent optimization (includes forward, backward, update). In a separate cell so that
### we don't re-initialize the network every time rendering our update weights function useless

for k in range(30): # Number of times we run the learning process
    ## 3.1 Forward pass
    x_encoded = F.one_hot(xs, num_classes=27).float() # one-hot encode the x-axis inputs
    logits = x_encoded @ Weights # predict the log-counts of the outputs characters based on the randomized weights. Softmax!
    counts = logits.exp() # get rid of the zeroes
    probability_tensor = counts / counts.sum(1, keepdims = True) # probabilities of the outputs averaged over the entire dataset
    loss = -probability_tensor[torch.arange(number_of_examples), ys].log().mean() # negative log likelihood (loss) of the data, which we are trying to minmize
    print(loss.item())

    ## 3.2 Backward pass
    Weights.grad = None # Zero the gradient
    loss.backward()

    ## 3.3 Update the weights -- given the loss is positive, we should try to decrease the weights
    Weights.data += -0.1 * Weights.grad # update the weights, reducing them to decrease the loss

    ## From here, every time you rerun this cell, it will update again. The -0.1 is the learning rate -- we could probably increase this, or we increase the number of times we run the learning process

0.09226502478122711
0.09145938605070114
0.09066691994667053
0.08988770097494125
0.08912106603384018
0.08836685121059418
0.08762483298778534
0.08689450472593307
0.08617596328258514
0.08546879887580872
0.0847725197672844
0.08408711850643158
0.08341237157583237
0.08274776488542557
0.08209340274333954
0.08144878596067429
0.08081398159265518
0.08018859475851059
0.07957233488559723
0.07896526902914047
0.07836687564849854
0.0777774378657341
0.07719624042510986
0.07662355154752731
0.0760587528347969
0.07550226151943207
0.07495330274105072
0.074412040412426
0.0738782212138176
0.07335181534290314


In [322]:
###### Now, we can sample from the trained neural net model (with updated weights per the gradient optimization) to see how it's actually performing qualitatively, as before! ######
for i in range(5):
    output = []
    index = 0

    while True:
        x_encoded = F.one_hot(torch.tensor([index]), num_classes=27).float()
        logits = x_encoded @ Weights # using the updated weights.data per adjustments via weights.grad after calculating the loss from that input data
        counts = logits.exp()
        probability_tensor = counts / counts.sum(1, keepdims=True) # probabilty distribution

        index = torch.multinomial(probability_tensor, num_samples=1, replacement=True, generator=g).item() # sampling an index based on the given probability distribution; ie. higher probability more likely to be chosen but not guaranteed
        output.append(itos[index])
        if index == 0:
            break
    
    print(''.join(output))



srellrvjdehqzgdshamxcnrvatsgionkkkjazlbqjjhcm.
.
.
.
.
